# .github/workflows/run-tests.yml in Repo2

name: Run Tests on Trigger

on:
  repository_dispatch:
    types: [run-tests]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo B code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies

    - name: Set PYTHONPATH for imports
      run: |
        echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV  # Set PYTHONPATH to the root of the app
        echo "PYTHONPATH: $PYTHONPATH"

    - name: Run pytest
      run: |
        pytest tests/test_example.py  # Run your test file
