name: Run Tests on Trigger
on:
  repository_dispatch:
    types: [run-tests]  # Listen for the 'run-tests' event
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo B code
      uses: actions/checkout@v2  # Check out the code from Repo2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Set Python version to 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt
    - name: Set PYTHONPATH for imports
      run: |
        echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV  # Set PYTHONPATH to include 'app' directory
    - name: Run pytest
      run: |
        pytest tests/test_example.py  # Run tests from tests/test_example.py
