name: Run Tests on Changes

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
    types: [run-tests]  
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo2 code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  
      - name: Set PYTHONPATH for imports
        run: |
          echo "PYTHONPATH=$(pwd)/app" >> $GITHUB_ENV  
          echo "PYTHONPATH: $PYTHONPATH"  

      - name: Run pytest
        run: |
          pytest tests/test_example.py  
